### task_1_Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### task_2_Numpy

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### task_3_Numpy

In [5]:
a_centered_sp = (a_centered[0][0]
                 * a_centered[1][0]
                 * a_centered[2][0]
                 * a_centered[3][0]
                 * a_centered[4][0]) + (a_centered[0][1]
                                        * a_centered[1][1]
                                        * a_centered[2][1]
                                        * a_centered[3][1]
                                        * a_centered[4][1])
a_centered_sp

-5.591040000000005

In [6]:
N = 5
a_centered_sp = a_centered_sp / (N - 1)
a_centered_sp

-1.3977600000000012

### task_4_Numpy

In [7]:
A = np.transpose(a)
A

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
B = np.cov(A)
B

array([[1. , 2. ],
       [2. , 4.3]])

### task_1_Pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [4]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### task_2_Pandas

In [5]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### task_3_Pandas

In [6]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### task_4_Pandas

In [7]:
# option 1
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})
authors_stat = authors_stat.reset_index()
authors_stat

author_name price                 
                min  max        mean
0  Островский   290  370  330.000000
1    Тургенев   300  450  366.666667
2       Чехов   450  500  475.000000

In [8]:
# option 2
min_price = authors_price.groupby('author_name').agg({'price': 'min'})
max_price = authors_price.groupby('author_name').agg({'price': 'max'})
mean_price = authors_price.groupby('author_name').agg({'price': 'mean'})

min_max_price = pd.merge(min_price, max_price, on = 'author_name', how = 'inner')
authors_stat = pd.merge(min_max_price, mean_price, on = 'author_name', how = 'inner')

authors_stat = authors_stat.reset_index()
authors_stat = authors_stat.rename(columns={'price_x': 'min_price', 'price_y': 'max_price', 'price': 'mean_price'})
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

### task_5_Pandas

In [10]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [11]:
?pd.pivot_table

In [15]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [19]:
book_info.to_pickle('book_info.pkl')

In [20]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950